### ISSUE TITLE
Stacked cards do not stay still when friction is 0?

### ISSUE THREAD

**Issue by HimeragiYukina** [ipc-sim/Codim-IPC#9]
Hi, I have built 4 test cases of stacked cards. But when the friction is set to 0, they do not work as expected. Without any forces other than gravity, the cards slide or even rotate. Besides, when the gravity is set to 0, the simulations of these test cases do not terminate and keep looping on searching alpha value. Also, the 3D meshes used in my test cases are the same as the meshes used in the file 8_precision_card_shuffle.py, and I am running the latest source code.

I wonder if my test cases are incorrect, there is a bug in the source code, the friction model is not appropriate, or anything else is wrong?

In all my test cases, I set the shells (cards and tables) apart by their thickness plus a 1e-5 offset; so, they are barely touching each other. The 4 test cases are designed as:
1. one_card_on_table.py: one card on a fixed table. Also, in this case, the simulation seems to be stuck in the loops of searching alpha value after frame 47.
2. three_cards_on_table.py: 3-card stack on a fixed table.
3. two_card_stack.py: 2-card stack, the bottom card is fixed.
4. three_card_stack.py: 3-card stack, the bottom card is fixed.

The code of my test cases is in the attached zip file. They can be run using the same way to run the C-IPC examples.
[stacked_cards_tests.zip](https://github.com/ipc-sim/Codim-IPC/files/9905337/stacked_cards_tests.zip)

**Comment by liminchen** [comment]
Hi Yunhao,

I have fixed the infinite loop issues you encountered in the
one_card_on_table and the one_card_above_table examples.

When the Newton residual is tiny, or say we are very close to the local
minimum, line search for alpha is expected to fail (ending up with a tiny
alpha) due to numerical rounding errors. But what the code did was,
whenever the searched alpha is tiny, the optimization will switch to
gradient descent in the next iteration, and the optimization loop won't
terminate if the last iteration was gradient descent. This design was
mainly for debugging purposes.

We didn't encounter any issues with this stopping criteria back then, but
your case is a nice example to reveal the problem with it. We have also
encountered similar issues in our later developments, and we have switched
to a stopping criteria based on only the current Newton residual (not the
previous 3 as in Codim-IPC), and we check whether NewtonRes < NewtonTol to
terminate the loop before line search. This will fix the issue perfectly in
our experience.

But to fix Codim-IPC with minimum change, what I just did was to make sure
that if tiny step size happens when the current Newton residual is smaller
than the Newton tolerence, then this iteration will be the last one. This
fixes the infinite loop issues for both one_card_above_table and
one_card_on_table, and now one_card_above_table does not slide under zero
friction.

However, one_card_on_table still slides under zero friction, which means
the current fix for the stopping criteria is not perfect — small numerical
perturbations can still create asymmetry in the contact forces, and these
later accumulate to visable motion artifacts. If needed, checking
convergence before line search should solve this issue.

In addition, I noticed that you used the cloth_thickness_iso when placing
the card. In fact, the cloth_thickness_iso is only used for calculating
volume and modulus in mass and elasticity computations, and it is not used
for contact. What is used for contact is the input arguments of the
sim.initialize_OIPC(dhat, xi) function, where dhat is the elastic
thickness, and xi is the geometric thickness. All initial distances must be
larger than xi.

Let me know if you have more questions!

Best,
Minchen
